apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
spec:
  selector:
    matchLabels:
      app: pgadmin
  replicas: 1
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:
      - name: pgadmin
        image: dpage/pgadmin4
        env:
        # Permet de gérer la route depuis l'ingress
        - name: SCRIPT_NAME
          value: /api/admin
        envFrom:
          - secretRef:
              name: pgadmin-secret
        ports:
        - containerPort: 80