# Ce Secret contient les informations d'identification de la base de données PostgreSQL pour FastAPI avec Traefik.
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
# Les données POSTGRES_USER et POSTGRES_PASSWORD sont encodées en base64.
data:
  POSTGRES_USER: "{{ .Values.secrets.db.user}}"
  POSTGRES_PASSWORD: "{{ .Values.secrets.db.password}}"
