apiVersion: v1
kind: Secret
metadata:
  name: pgadmin-secret
type: Opaque
data:
  PGADMIN_DEFAULT_EMAIL: "{{ .Values.secrets.pgadmin.email}}"
  PGADMIN_DEFAULT_PASSWORD: "{{ .Values.secrets.pgadmin.password}}"