apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
spec:
  ingressClassName: traefik
  # tls:
  #   - secretName: 
  #     hosts:
  #       - 
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
        # Path api web
        - path: /
          pathType: Exact
          backend:
             service:
              name: web-service
              port:
                number: 8000
        # Path pgAdmin
        - path: "{{ .Values.pgadmin.config.script_name }}"
          pathType: Prefix
          backend:
             service:
              name: pgadmin-service
              port:
                number: 8080
        # Path kibana
        - path: "{{ .Values.kibana.config.server_basepath }}"
          pathType: Prefix
          backend:
             service:
              name: kibana-service
              port:
                number: 5601
        # Path dashboard traefik
        - path: /dashboard
          pathType: Prefix
          backend:
             service:
              name: {{ .Values.dashboardService.name }}
              port:
                name: {{ .Values.dashboardService.name }}