apiVersion: apps/v1
kind: Deployment
metadata:
  name: traefik-deployment

spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
    spec:
      serviceAccountName: traefik-service-account
      containers:
      - name: traefik
        image: traefik:v2.9.6
        args:
            - --api.insecure
            - --providers.kubernetesingress
        ports:
            - name: web
              containerPort: 80
            - name: dashboard
              containerPort: 8080