apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: traefik-role
rules:
- apiGroups: [""]
  resources: ["services", "pods", "endpoints", "secrets", "ingresses"]
  verbs: ["get", "list", "watch"]
