namespace: dev

web:
  repository: kbnhvn/web-dev
  tag: latest

data:
  tag: latest

nginx:
  tag: latest

ingress:
  host: dev.localhost

role:
  name: traefik-role-dev

roleBinding:
  name: traefik-role-binding-dev

