apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch
  namespace: standard
spec:
  serviceName: elasticsearch-service
  selector:
    matchLabels:
      app: elasticsearch
  replicas: 1
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
        envFrom:
          - configMapRef:
              name: elasticsearch-configmap
        volumeMounts:
        - mountPath: /usr/share/elasticsearch/data
          name: elasticsearch-data
        ports:
        - containerPort: 9200
      volumes:
      - name: elasticsearch-data
        persistentVolumeClaim:
          claimName: elasticsearch-pvc