apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
spec:
  serviceName: kibana-service
  selector:
    matchLabels:
      app: kibana
  replicas: 1
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
      - name: kibana
        image: docker.elastic.co/kibana/kibana:7.5.2
        envFrom:
          - configMapRef:
              name: kibana-configmap
        ports:
        - containerPort: 5601